# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'wild5' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for wild5
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-RCTPushNotification', :path =>
  '../node_modules/react-native/Libraries/PushNotificationIOS'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RollbarReactNative', path: '../node_modules/rollbar-react-native/'

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Database', '~> 6.3.0'

  #node_modules packages? 
  pod 'ReactNativeAudioToolkit', path: '../node_modules/@react-native-community/audio-toolkit'
  pod 'RNDateTimePicker', path: '../node_modules/@react-native-community/datetimepicker'
  pod 'RNCMaskedView', path: '../node_modules/@react-native-community/masked-view'
  pod 'react-native-netinfo', path: '../node_modules/@react-native-community/netinfo'
  pod 'react-native-slider', path: '../node_modules/@react-native-community/slider'
  pod 'react-native-config', path: '../node_modules/react-native-config'
  pod 'ReactNativeExceptionHandler', path: '../node_modules/react-native-exception-handler'
  pod 'RNFirebase', path: '../node_modules/react-native-firebase/ios'
  pod 'RNGestureHandler', path: '../node_modules/react-native-gesture-handler'
  pod 'RNReanimated', path: '../node_modules/react-native-reanimated'
  pod 'react-native-safe-area-context', path: '../node_modules/react-native-safe-area-context'
  pod 'RNScreens', path: '../node_modules/react-native-screens'
  pod 'RNSVG', path: '../node_modules/react-native-svg'
  pod 'RNVectorIcons', path: '../node_modules/react-native-vector-icons'
  pod 'BVLinearGradient', path: '../node_modules/react-native-linear-gradient'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-config'
        phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
        phase.shell_script = "cd ../../"\
        " && RNC_ROOT=./node_modules/react-native-config/"\
        " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
        " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
        
        target.build_phases << phase
        target.build_phases.move(phase,0)
      end
    end
    use_native_modules!
  end
 

end